### ISSUE TITLE
Do we need diff feature?

### ISSUE THREAD

**Issue by theaqua** [theaqua/redux-logger#136]
Hi, guys! When I made `redux-logger`, I'm also made [redux-diff-logger](https://github.com/fcomb/redux-diff-logger). Suddenly `redux-logger` became more popular than it's brother and now I want to add diff to `redux-logger` and deprecate `redux-diff-logger`. As part of options, `const logger = createLogger({ diff: true })`.

What do you think? Will it be useful as part of `redux-logger`?

**Comment by epeli** [comment]
How much would it add weight to the library?

**Comment by theaqua** [comment]
@epeli to be honest, I don't know which library I'll use. I had the plan to use [jsondiffpatch](https://github.com/benjamine/jsondiffpatch), but it looks like swiss-army-knife.

**Comment by theaqua** [comment]
@epeli by the way, is the weight is a problem? I think `redux-logger` by default used only in development mode.

**Comment by epeli** [comment]
No necessarily but with the current very tiny footprint I can just leave it in for production, disabled, but with a possibility to enable it with a local storage flag if I ever need to debug something in production. 

Also it would be a bit of an hassle to strip it out for production builds.

**Comment by jonaskello** [comment]
+1 for merging diffing into this lib. Also it would be nice if it could somehow use the existing stateTransformer so we could diff state that uses Immutable. Or even better if Immutable was supported by default.

**Comment by theaqua** [comment]
@epeli ah, I see.

@jonaskello Immutable will be supported by `stateTrasformer`.

**Comment by smashercosmo** [comment]
Totally for merging redux-logger and redux-diff-logger. 
@epeli for debugging in production you can always use redux-devtools chrome extension.

**Comment by ms88privat** [comment]
:+1: It is nice to have the config object for diff-logger too!

**Comment by tomauty** [comment]
Wow, yes please!

**Comment by axs221** [comment]
+1 for merging the two solutions. We have both enabled. It isn't very useful that the diff logger shows up in a different console group. Being asynchronous it can also show up disjoint with the redux-logger statements. And the diff logger doesn't have the same features, not showing the same action information.

**Comment by janslow** [comment]
+1 for merging the two

**Comment by sibeliusseraphini** [comment]
👍

**Comment by sibeliusseraphini** [comment]
I've just merged redux-diff-logger with redux-logger in this PR https://github.com/theaqua/redux-logger/pull/149

this is the current screenshot of my implementation:

![screen shot 2016-05-10 at 18 39 40](https://cloud.githubusercontent.com/assets/2005841/15163800/1003ba98-16e1-11e6-97e2-c897bee92a0a.png)

**Comment by jonaskello** [comment]
Nice! Could we have a new npm package with the diffing feature?

**Comment by toxickg** [comment]
We're going to release the new version after fixing [array diff issue](https://github.com/fcomb/redux-diff-logger/issues/1) as well as other corner cases.

**Comment by liorbrauer** [comment]
Question: what about support for ImmutableJS states? It could be useful and work in conjunction with the stateTransformer option, to simply pass its return value to the diff algorithm.

**Comment by jonaskello** [comment]
One idea would be to do the diffing using a [jsonpatch](http://jsonpatch.com) framework and then just present the raw patches. For example just calling [json8.diff](https://github.com/JSON8/patch#diff) and then presenting the results directly. This would be enough for my requirements anyway. I guess state transformation from immutable could be added before sending it to json8. I have not used json8 myself, only other jsonpatch frameworks, but it looks quite straightforward. There is also [jiff](https://github.com/cujojs/jiff) which seems to do the same thing. I have probably overlooked something in this solution so please forgive my ignorance on the matter.

**Comment by toxickg** [comment]
@jonaskello, thank you for your suggestions! In the first place, we considered [jsondiffpatch](https://github.com/benjamine/jsondiffpatch) for carrying out the diffing part. But I think we should also take [json8-patch](https://www.npmjs.com/package/json8-patch) into account.

**Comment by toxickg** [comment]
@liorbrauer, how exactly do you suggest to use `stateTransformer` along with Immutable.js?
