### ISSUE TITLE
Fine-grained control over level again

### ISSUE THREAD

**Issue by sergej-s** [theaqua/redux-logger#142]
Hello! 
Thanks for really helpfull lib.

I am wondering how I can hide prev and next states logging based on action type. I.e. something like this:
`level: {prevState: (action) => (action.type === 'SERVER_LOG_MESSAGE') ? false : 'info')}`

But prevState and nextState funcs get state as argument instead of action. Is it possible to add action as second parameter?
`prevState: (state, action) => (action.type === 'SERVER_LOG_MESSAGE') ? false : 'info')`

**Comment by theaqua** [comment]
Don't understand. For what? It's breaking change.

**Comment by sergej-s** [comment]
At the moment it is possible to hide logging of prevState or nextState depending on state. But I'd like to hide it depending on some action data. To get something like this:

If action.type === 'SOME_ACTION' then:
![image](https://cloud.githubusercontent.com/assets/668587/14174212/9e72f650-f74b-11e5-9cce-52e3e6b6c034.png)

How can I do this?

**Comment by fabiosussetto** [comment]
@sergej-s not sure if I got your question right, but I achieved something (possibly) similar to what you're asking by using this from the docs:
https://github.com/fcomb/redux-logger#predicate--getstate-function-action-object--boolean

**Comment by theaqua** [comment]
@sergej-s ah, I see your point. Wrongly read at the first time.
Can you make PR?

**Comment by sergej-s** [comment]
@theaqua, thank you. I try to make PR in near days.
