### ISSUE TITLE
Suppress specific logs?

### ISSUE THREAD

**Issue by FezVrasta** [theaqua/redux-logger#150]
I have an action performed each second (to update stuff, I know, it sucks, but you know...)

I'd like to suppress the logs for this specific action, is it possible?

**Comment by AugustinLF** [comment]
This [recipe](https://github.com/theaqua/redux-logger#log-everything-except-actions-with-type-auth_remove_token) from the readme should help you :)

**Comment by FezVrasta** [comment]
great thanks!

**Comment by theaqua** [comment]
Correct link: https://github.com/theaqua/redux-logger#log-everything-except-actions-with-certain-type
